/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_w77996_uninstalldemo_UnInstallJni */

#ifndef _Included_com_w77996_uninstalldemo_UnInstallJni
#define _Included_com_w77996_uninstalldemo_UnInstallJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_w77996_uninstalldemo_UnInstallJni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_w77996_uninstalldemo_UnInstallJni_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
